on: [ push ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }},
  GITHUB_REPOSITORY: 'akunopaka/leetcode/README.md'
jobs:
  readme_leetcode_table_update_job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Readme.md Auto Update - Leetcode Solutions Table
    steps:
      - uses: actions/checkout@v3
      - uses: akunopaka/leetcode/.gitAction/@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: 'akunopaka/leetcode/README.md'
